### ISSUE TITLE
Book erratum: Different distances

### ISSUE THREAD

**Issue by gabraganca** [astroML/text_errata#31]
I am preparing a class where I am going to use the *Statistics Data Mining, and Machine Learning in Astronomy* book. I think I run into something strange in section 2.5.2. I hope this is the right place to address this.

The distances calculated by the `easy_nn` and `vectorized_nn`are not the same. I think it lacks a square root at equations 2.4, 2.5 and 2.6. 

I [set up a notebook](http://nbviewer.jupyter.org/gist/gabraganca/3e13ed66b240d16d9206) showing this.

**Comment by jakevdp** [comment]
Indeed! Thank you for the report; I've added this in 3b81708cc55a1619417b195a0642e5cf1b407967
