### ISSUE TITLE
Eqns 8.67 and 8.68

### ISSUE THREAD

**Issue by joel-roediger** [astroML/text_errata#36]
Hi,

I wonder if eqns 8.67 and 8.68 contain a similar error.  Should sigma_i^2 not appear in the second term of the likelihood function?  The second term reflects the background component, so why should the statistics of it have anything to do with sigma_i?

Cheers,
Joel Roediger

**Comment by ivezic** [comment]
Hi Joel,

thanks for your question. I think one could argue both ways. Your claim is correct
if the outliers somehow “know” nothing about the measurements (as if coming
from some other "totally different population”). If instead V_b implies a source of
error *in addition* to the already existing measurement error for each point,
then eqns. in the book are ok.

We will add a clarification of this distinction to the second edition and I just
added your comment to the book errata at
https://github.com/astroml/text_errata

       Thanks again!
       Cheers, Zeljko

**Comment by ivezic** [comment]
Implemented. Thanks Joel!
